### ISSUE TITLE
Create new page with CRUD operations - Orders

### ISSUE THREAD

**Issue by Magik3a** [PrintGroundLtd/PGMS#11]
```
a.	ID
b.	User working on offer
c.	Account or Company
d.	Width
e.	Height
f.	Product (foreign field Products)
g.	Quantity or m2 
h.	Price per qt.
i.	Percent +/-
j.	Payment Type (foreign field - Payment types)
k.	Total price (auto completed from price per qt or m2 and percent) 
i.       Status (foreign field  - Order Statuses)
m.	Notes?
n.	From partner (foreign field Partners)

```

**Comment by PrintGroundLtd** [comment]
Add to accounts Orders and Outside Orders as a new tabs and grids 
![image](https://user-images.githubusercontent.com/37100856/38733654-661d305c-3f2b-11e8-825c-0dd62d4f1ae2.png)

**Comment by PrintGroundLtd** [comment]
add new grid and checkbox to orders. If Order is ongoing show the order for each logged in user in the dashboard 
![image](https://user-images.githubusercontent.com/37100856/38733775-e77cf006-3f2b-11e8-9b66-74f5ff1e3b3a.png)

**Comment by PrintGroundLtd** [comment]
add notes --> 
![image](https://user-images.githubusercontent.com/37100856/38734152-2f85a838-3f2d-11e8-9e2e-12f4953dbe8b.png)

**Comment by PrintGroundLtd** [comment]
![image](https://user-images.githubusercontent.com/37100856/38734663-19b3db36-3f2f-11e8-8580-37b2bf9c90cc.png)

**Comment by PrintGroundLtd** [comment]
![image](https://user-images.githubusercontent.com/37100856/38734770-70a79bda-3f2f-11e8-8bb5-7db188013b4b.png)

**Comment by Magik3a** [comment]
Added Notes and inplace add for each dropdown. Every user with permissions for updating the field will have this

**Comment by Magik3a** [comment]
![image](https://user-images.githubusercontent.com/10474555/38894762-db069606-4296-11e8-8999-c634b080777f.png)

**Comment by Magik3a** [comment]
added grouping functionalyties and some styles to orders 
![image](https://user-images.githubusercontent.com/10474555/39149164-ec2b2abe-4746-11e8-9051-b577716ff242.png)
