### ISSUE TITLE
Order Details dialog

### ISSUE THREAD

**Issue by PrintGroundLtd** [PrintGroundLtd/PGMS#30]
After we addd new product to order detail with discount of 1,74 after we save the order the total value and the discount are calculated by 2 
![image](https://user-images.githubusercontent.com/37100856/40794443-dbdb718a-6507-11e8-8282-b20820d5d6ec.png)

**Comment by Magik3a** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/10474555/41050524-4f03e300-69bc-11e8-9748-40d0aeea713c.png)
