### ISSUE TITLE
Autopopulate the name when expense is made from order or outside order

### ISSUE THREAD

**Issue by PrintGroundLtd** [PrintGroundLtd/PGMS#32]
When new expense is made from order or outside order autopopuplate the name from the order in this format: 

Expense - Order (#Number)
Expense - Outside Ouder (#Number) 

![image](https://user-images.githubusercontent.com/37100856/40795989-54aa7972-650c-11e8-999b-6c7058b5d43f.png)

**Comment by Magik3a** [comment]
![image](https://user-images.githubusercontent.com/10474555/41055479-1e6bd76c-69ca-11e8-9fe1-2f458c8b8412.png)
![image](https://user-images.githubusercontent.com/10474555/41055509-35dd204a-69ca-11e8-9af4-7928ce95bc87.png)
