### ISSUE TITLE
Added quickfilter for propertie With Vat 

### ISSUE THREAD

**Issue by PrintGroundLtd** [PrintGroundLtd/PGMS#35]
In payment tab --> 

![image](https://user-images.githubusercontent.com/37100856/41088096-44b58986-6a47-11e8-8dee-cdee37ea76ed.png)

Add button --> "Show orders only with VAT", thus when clicked, only orders with VAT to be displayed and combined with the "Group of type of payment" the result to be: all payments income with VAT only to be visible as well with all payments outcome with VAT only to be visible!

**Comment by Magik3a** [comment]
Added fpr expenses, orders and ouside orders 
![image](https://user-images.githubusercontent.com/10474555/48329548-f6134e80-e651-11e8-8b3b-3142c7728aa2.png)
