### ISSUE TITLE
Regarding payments

### ISSUE THREAD

**Issue by PrintGroundLtd** [PrintGroundLtd/PGMS#37]
Regarding order number --> 279 !

If you go to Orders menu --> order number 279, further payments -->
![image](https://user-images.githubusercontent.com/37100856/41833930-fb8bb13c-785a-11e8-95ef-414c00b35139.png)
There is only 1 payment visible.
However if you go to Payments menu --> I can see 2 payments regarding the very same order there.
This is weird -->
![image](https://user-images.githubusercontent.com/37100856/41834002-4243533c-785b-11e8-96f3-4f07ff36a798.png)
If the 1st payment was visible (this is why I have created the 2nd) it mislead me.
Can you please have a look?
Thanks in advance!

**Comment by Magik3a** [comment]
The payment is not made for Order, 
![image](https://user-images.githubusercontent.com/10474555/41844650-79bc88f6-7879-11e8-99ed-aca6ff880259.png)
i edited Payment ID 1319 and i added order id 279
![image](https://user-images.githubusercontent.com/10474555/41844746-ce2d5f00-7879-11e8-8212-610cf64eef24.png)
