### ISSUE TITLE
When there is no action for couple of minutes, throws error  

### ISSUE THREAD

**Issue by Magik3a** [PrintGroundLtd/PGMS#64]
Not able to reproduce this on local servers.

**Comment by Magik3a** [comment]
This is not reproducable on Development server @BozhidarVladimirov

**Comment by BozhidarVladimirov** [comment]
@Magik3a I can provide you with step by step instructions as well with the exact time of the issue. Would that help to check server logs and see what is causing this problem?

**Comment by Magik3a** [comment]
Moved to https://github.com/Magik3a/PrintCenter-ERP/issues/21
